---
apiVersion: v1
kind: List
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: heketi-exporter
    annotations:
      description: The heketi Exporter port
  spec:
    ports:
    - name: scrape
      port: 9189
      targetPort: 9189
    selector:
      name: heketi-exporter
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: heketi-exporter
    labels:
    app: heketi-exporter
  spec:
    replicas: 1
    selector:
      name: heketi-exporter
    template:
      metadata:
        labels:
          name: heketi-exporter
      spec:
        containers:
          - name: heketi-exporter
            image: 10.0.3.47:5000/heketi-exporter:latest
            imagePullPolicy: Always
            env:
            - name: HEKETI_CLI_USER
              value: admin
            - name: HEKETI_CLI_KEY
              value: "<CHANGE ME>"
            - name: HEKETI_CLI_SERVER
              value: "<CHANGE ME>"
            ports:
              - containerPort: 9189
                protocol: TCP
            resources:
              requests:
                cpu: 10m
                memory: 200Mi
            terminationMessagePath: /dev/termination-log
            securityContext:
              capabilities: {}
              privileged: false
        restartPolicy: Always
